### ISSUE TITLE
Add @Size support

### ISSUE THREAD

**Issue by lgueye** [jpdigital/hibernate5-ddl-maven-plugin#3]
Hi all,

First thank you a lot since you were the only plugin to be at the same straightforward to configure and working flawlessly.

But I found out  that the @Size attribute was not taken into account in the generation thus generating the default 255 varchar size.

Thank you for your help

**Comment by jpdigital** [comment]
Hello Igueye,

I'm not sure to what exactly you are referring. You write `@Size` which indicates that you are referring to annotation, but than you write attribute...

If you are referring to the `size` attribute of the `@Column` annotation: I'm quite sure that is working because I have several usages of that attribute in my projects. If that is not working it would be helpful if you can provide an example.

If you are referring to an `@Size` annotation: Neither JPA nor Hibernate itself provide such an Annotation. If your referring to an annotation I suspect that you mean annotation from the Bean Validation API, `javax.validation.constraints.Size`, and expect that this annotation is used to determine the size of your varchar column. This will not work because it is not an JPA or Hibernate annotation. 

Best regards

Jens

**Comment by lgueye** [comment]
Hi @jpdigital . Thank you very much for the clarification.
Indeed it was a misusage of the API (the size is controlled by the @Column size attribute, not the @Size Bean Validation annotation. 
You can close the issue

**Comment by jpdigital** [comment]
Hello lgueye,

no problem. Sometimes the various annotations can be very confusing... 

Best regards

Jens
