### ISSUE TITLE
"cascade" property of @OneToMany and @ManyToOne is not reflected in SQL

### ISSUE THREAD

**Issue by gerrit-hohl** [jpdigital/hibernate5-ddl-maven-plugin#7]
Maybe this is more like a question than a bug. But I realized that the "cascade" property of @OneToMany and @ManyToOne is not reflected in the SQL statements.

I'm using Apache Derby 10.13 and currently I'm using the DB2 dialect as the hibernate5-ddl-maven-plugin doesn't support Derby natively yet (see issue #6). I have specified CascadeType.ALL in both cases and would have expected - as the standard `ON DELETE` and `ON UPDATE` action is `NO ACTIONS` (see [CONSTRAINTS clause - Referential actions](https://db.apache.org/derby/docs/10.13/ref/rrefsqlj13590.html#rrefsqlj13590__referactions)) - would be `ON UPDATE CASCADE ON DELETE CASCADE`.

Maybe my expectation is just wrong. Or maybe the current situation only exists because there is no native Derby support in the plugin.

**Comment by jpdigital** [comment]
Hello,

I think your expect ion is not correct. Because not all databases support the CASCADE feature Hibernate may implements this feature without reflecting it in the SQL. I just checked one of my own projects were I also used the `cascade` property and PostgreSQL 9 as database. No sign of `ON UPDATE` in the SQL, but it works.

Please note that the plugin does nothing more than calling the `SchemaExport` class from Hibernate. In essence, this plugin in merely a wrapper around the `SchemaExport`. Maybe the Hibernate forums are a better place for your question.
